Algoritmo "exercicio0025"

Var
// Seção de Declarações das variáveis 
musica: caracter
compositor: caracter
entrada: caracter
saida:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
musica<-"Sampa"
compositor<-"Caetano Veloso"
entrada<-musica+"/"+compositor
saida<-"Música:"+musica+"Compositor:"+compositor

Escreval(entrada)
Escreval(saida)

Fimalgoritmo